ALTER TABLE employees
    ADD COLUMN IF NOT EXISTS serial_number VARCHAR(50),
    ADD COLUMN IF NOT EXISTS contract_number VARCHAR(100),
    ADD COLUMN IF NOT EXISTS branch_id BIGINT,
    ADD COLUMN IF NOT EXISTS contract_end_date DATE,
    ADD COLUMN IF NOT EXISTS annual_leave_duration INTEGER DEFAULT 30,
    ADD COLUMN IF NOT EXISTS annual_leave_balance INTEGER DEFAULT 30,
    ADD COLUMN IF NOT EXISTS group_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS salary NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS hourly_rate NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS allowance VARCHAR(255),
    ADD COLUMN IF NOT EXISTS emergency_contact VARCHAR(255),
    ADD COLUMN IF NOT EXISTS address TEXT,
    ADD COLUMN IF NOT EXISTS notes TEXT;
