ALTER TABLE leaves ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE leaves ADD COLUMN IF NOT EXISTS approved_by BIGINT;
ALTER TABLE leaves ADD COLUMN IF NOT EXISTS approval_date TIMESTAMP;
ALTER TABLE leaves ADD COLUMN IF NOT EXISTS reason TEXT;
ALTER TABLE leaves ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'PENDING';

UPDATE leaves SET created_at = COALESCE(created_at, NOW());
UPDATE leaves SET updated_at = COALESCE(updated_at, NOW());

ALTER TABLE leaves ALTER COLUMN created_at SET DEFAULT NOW();
ALTER TABLE leaves ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE leaves ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE leaves ALTER COLUMN updated_at SET NOT NULL;
